from scratch
copy bin/server .

copy build/. build/
copy .env .
copy pkg/server/posts/interfaces/schema/postgresql.sql schema/post.sql
copy pkg/server/newsletter/interfaces/schema/postgresql.sql schema/newsletter.sql

entrypoint ["/server"]
